/** Generated by TAP **/
KISSY.config({
    "combine": true,
    "modules": {},
    "packages": {
        "mui/dlp": {
            "version": "4.0.0",
            "path": "//g.alicdn.com/mui/dlp/4.0.0/",
            "group": "tm",
            "ignorePackageNameInUri": true,
            "debug": true
        }
    }
});